#!/usr/bin/env bash

echo " "
echo "  _____  ______ __  __  ______      ________ "
echo " |  __ \|  ____|  \/  |/ __ \ \    / /  ____|"
echo " | |__) | |__  | \  / | |  | \ \  / /| |__   "
echo " |  _  /|  __| | |\/| | |  | |\ \/ / |  __|  "
echo " | | \ \| |____| |  | | |__| | \  /  | |____ "
echo " |_|  \_\______|_|  |_|\____/   \/   |______|"
echo "                                             "
echo "                                             "
echo "  _____       _______        _____ ______ _______ _____ _ "
echo " |  __ \   /\|__   __|/\    / ____|  ____|__   __/ ____| |"
echo " | |  | | /  \  | |  /  \  | (___ | |__     | | | (___ | |"
echo " | |  | |/ /\ \ | | / /\ \  \___ \|  __|    | |  \___ \| |"
echo " | |__| / ____ \| |/ ____ \ ____) | |____   | |  ____) |_|"
echo " |_____/_/    \_\_/_/    \_\_____/|______|  |_| |_____/(_)"
echo "                                                          "
echo " "

inputFile=$1
outFile=temp.py

function printerLoop {
    sample=$1
    shift
    echo "$sample = {"                                                                >> $outFile
    while [ $# -gt 0 ] ; do 
        echo "    '$1': [`grep "^$1 " $inputFile | awk 'BEGIN{a="'"'"'"} NF==3{ print a$2a","a$3a } NF==4{ print a$2a","$3","a$4a }'`]," >> $outFile
        shift
    done
    echo "}"                                                                          >> $outFile
    echo                                                                              >> $outFile
}

data="`for x in 12 13 15 16; do for y in 0 1 2 3 4; do echo $x$y; done; done`"
ww="`for x in $(seq 0 1); do echo 00$x; done`"
wwSys="`for x in $(seq 2 4); do echo 00$x; done`"
ggWW="001"
ttbar="010"
top="`for x in $(seq 0 6); do echo 01$x; done`"
tW="`for x in $(seq 1 6); do echo 01$x; done`"
tWSys="`for x in $(seq 7 8); do echo 01$x; done`"
dy="`for x in $(seq 0 5); do echo 03$x; done`"
zGam="038 039 040 041"
dyMad="037"
wz="070"
zz="071"
diBoson="`for x in $(seq 0 3); do echo 07$x; done`"
wJet="080"
wGam="082 083 084"
vGam="081"

hSamples="1 2 3 4 5 6"

echo "import FWCore.ParameterSet.Config as cms" > $outFile
echo "from glob import glob" >> $outFile
echo >> $outFile

printerLoop dataSamples  $data
printerLoop allBackgroundSamples $ww $ggWW $ttbar $top $tW $dy $wz $zz $diBoson $wJet 
printerLoop allOtherBackgrounds $wwSys $tWSys $zGam $dyMad $wGam $vGam
printerLoop allSignalSamples `for x in $(seq 120 10 230) $(seq 250 50 600); do for y in $hSamples; do echo $y$x; done; done`

printerLoop wwSamples $ww
printerLoop wwSysSamples $wwSys
printerLoop ggWWSample $ggWW
printerLoop ttbarSamples  $ttbar
printerLoop topSamples $top
printerLoop tWSamples $tW
printerLoop tWSysSamples $tWSys
printerLoop dySamples   $dy
printerLoop zGamSamples  $zGam
printerLoop dyMadSamples    $dyMad
printerLoop wzSamples $wz
printerLoop zzSamples $zz
printerLoop diBosonSamples $diBoson
printerLoop wJetSamples    $wJet
printerLoop wGamSamples  $wGam
printerLoop vGamSamples  $vGam

for x in `seq 120 10 230` `seq 250 50 600`; do 
    printerLoop h${x}Samples `for y in $hSamples; do echo $y$x; done`
done

