#!/usr/bin/env bash

inputFile=$1
outFile=temp.py

function printerLoop {
    sample=$1
    shift
    echo "$sample = {"                                                                >> $outFile
    while [ $# -gt 0 ] ; do 
        echo "    '$1':  ['`grep ID$1 $inputFile | c 2`', `grep ID$1 $inputFile | c 3`]," >> $outFile
        shift
    done
    echo "}"                                                                          >> $outFile
    echo                                                                              >> $outFile
}

data="dataSamples    `for x in $(seq 73 82); do echo -n "0$x "; done`"
allBackground="allBackgroundSamples 001 002 003 004 005 017B 018B 023 010 011 012 014 022 021 026"
diBoson="diBosonSamples 001 002"
wz="wzSamples 001"
zz="zzSamples 002"
dy="dySamples      003 004 005 017B 018B"
top="topSamples 023 010 011 012"
ttbar="ttbarSamples   023"
tW="tWSamples 010 011 012"
ww="wwSamples      014 022"
ww2="wwSample 014"
ggWW="ggWWSample 022"
wJet="wJetSamples    026"
wGam="wGamSamples    021"
dyMad="dyMadSamples    027 028"

hSamples="101 102 103 104 105 106"

echo "import FWCore.ParameterSet.Config as cms" > $outFile
echo "from glob import glob" >> $outFile
echo >> $outFile

printerLoop $data
printerLoop $allBackground
printerLoop $diBoson
printerLoop $wz
printerLoop $zz
printerLoop $dy
printerLoop $top
printerLoop $ttbar
printerLoop $tW
printerLoop $ww
printerLoop $ww2
printerLoop $ggWW
printerLoop $wJet
printerLoop $wGam
printerLoop $dyMad

for x in `seq 120 10 200` `seq 250 50 600`; do 
    printerLoop h${x}Samples `for y in $hSamples; do echo $y$x; done`
done

printerLoop allSignalSamples `for x in $(seq 120 10 200) $(seq 250 50 600); do for y in $hSamples; do echo $y$x; done; done`
