#!/bin/bash

SCENARIO=$1; shift;
if [[ "$SCENARIO" == "" ]]; then echo "Usage: $0 scenario [ids]"; exit 1; fi;

IDS="all id iso hlt mu9 mu15"
if [[ "$*" != "" ]]; then IDS="$*"; fi;

for I in $IDS; do 
    cmsRun fitMuonID.py $SCENARIO $I 2>&1 | tee fitMuonID.$SCENARIO.$I.log;
done
